site_name: mlops_demo
site_description: Documentation for mlops_demo
docs_dir: 'docs'
site_dir: 'site'
theme:
  name: material
markdown_extensions:
  - toc:
      permalink: "#"
nav:
  - Home: 'index.md'
